// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Info          *HostInfo              `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	Usage         *ResourceUsage         `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostMetrics) Reset() {
	*x = HostMetrics{}
	mi := &file_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMetrics) ProtoMessage() {}

func (x *HostMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMetrics.ProtoReflect.Descriptor instead.
func (*HostMetrics) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *HostMetrics) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostMetrics) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HostMetrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HostMetrics) GetInfo() *HostInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *HostMetrics) GetUsage() *ResourceUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type HostInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UptimeSeconds     int64                  `protobuf:"varint,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	CpuCores          int32                  `protobuf:"varint,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	TotalMemoryBytes  int64                  `protobuf:"varint,3,opt,name=total_memory_bytes,json=totalMemoryBytes,proto3" json:"total_memory_bytes,omitempty"`
	TotalStorageBytes int64                  `protobuf:"varint,4,opt,name=total_storage_bytes,json=totalStorageBytes,proto3" json:"total_storage_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *HostInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HostInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *HostInfo) GetTotalMemoryBytes() int64 {
	if x != nil {
		return x.TotalMemoryBytes
	}
	return 0
}

func (x *HostInfo) GetTotalStorageBytes() int64 {
	if x != nil {
		return x.TotalStorageBytes
	}
	return 0
}

type ResourceUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent       float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	UsedMemoryBytes  int64                  `protobuf:"varint,2,opt,name=used_memory_bytes,json=usedMemoryBytes,proto3" json:"used_memory_bytes,omitempty"`
	UsedStorageBytes int64                  `protobuf:"varint,3,opt,name=used_storage_bytes,json=usedStorageBytes,proto3" json:"used_storage_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_proto_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceUsage) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceUsage) GetUsedMemoryBytes() int64 {
	if x != nil {
		return x.UsedMemoryBytes
	}
	return 0
}

func (x *ResourceUsage) GetUsedStorageBytes() int64 {
	if x != nil {
		return x.UsedStorageBytes
	}
	return 0
}

type Acknowledgment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgment) Reset() {
	*x = Acknowledgment{}
	mi := &file_proto_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgment) ProtoMessage() {}

func (x *Acknowledgment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgment.ProtoReflect.Descriptor instead.
func (*Acknowledgment) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *Acknowledgment) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Acknowledgment) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Wrapper for messages from outpost to collector
type OutpostMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OutpostMessage_Metrics
	//	*OutpostMessage_ScriptResult
	Payload       isOutpostMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutpostMessage) Reset() {
	*x = OutpostMessage{}
	mi := &file_proto_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutpostMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutpostMessage) ProtoMessage() {}

func (x *OutpostMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutpostMessage.ProtoReflect.Descriptor instead.
func (*OutpostMessage) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *OutpostMessage) GetPayload() isOutpostMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OutpostMessage) GetMetrics() *HostMetrics {
	if x != nil {
		if x, ok := x.Payload.(*OutpostMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *OutpostMessage) GetScriptResult() *ScriptResult {
	if x != nil {
		if x, ok := x.Payload.(*OutpostMessage_ScriptResult); ok {
			return x.ScriptResult
		}
	}
	return nil
}

type isOutpostMessage_Payload interface {
	isOutpostMessage_Payload()
}

type OutpostMessage_Metrics struct {
	Metrics *HostMetrics `protobuf:"bytes,1,opt,name=metrics,proto3,oneof"`
}

type OutpostMessage_ScriptResult struct {
	ScriptResult *ScriptResult `protobuf:"bytes,2,opt,name=script_result,json=scriptResult,proto3,oneof"`
}

func (*OutpostMessage_Metrics) isOutpostMessage_Payload() {}

func (*OutpostMessage_ScriptResult) isOutpostMessage_Payload() {}

// Wrapper for messages from collector to outpost
type CollectorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CollectorMessage_Ack
	//	*CollectorMessage_ScriptCommand
	Payload       isCollectorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorMessage) Reset() {
	*x = CollectorMessage{}
	mi := &file_proto_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorMessage) ProtoMessage() {}

func (x *CollectorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorMessage.ProtoReflect.Descriptor instead.
func (*CollectorMessage) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *CollectorMessage) GetPayload() isCollectorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CollectorMessage) GetAck() *Acknowledgment {
	if x != nil {
		if x, ok := x.Payload.(*CollectorMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *CollectorMessage) GetScriptCommand() *ScriptCommand {
	if x != nil {
		if x, ok := x.Payload.(*CollectorMessage_ScriptCommand); ok {
			return x.ScriptCommand
		}
	}
	return nil
}

type isCollectorMessage_Payload interface {
	isCollectorMessage_Payload()
}

type CollectorMessage_Ack struct {
	Ack *Acknowledgment `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type CollectorMessage_ScriptCommand struct {
	ScriptCommand *ScriptCommand `protobuf:"bytes,2,opt,name=script_command,json=scriptCommand,proto3,oneof"`
}

func (*CollectorMessage_Ack) isCollectorMessage_Payload() {}

func (*CollectorMessage_ScriptCommand) isCollectorMessage_Payload() {}

// Script to be executed on outpost
type ScriptCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScriptId      string                 `protobuf:"bytes,1,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`       // Unique identifier for the script
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                         // Script content (bash/shell script)
	Sha256Hash    string                 `protobuf:"bytes,3,opt,name=sha256_hash,json=sha256Hash,proto3" json:"sha256_hash,omitempty"` // Hash for deduplication and verification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptCommand) Reset() {
	*x = ScriptCommand{}
	mi := &file_proto_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptCommand) ProtoMessage() {}

func (x *ScriptCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptCommand.ProtoReflect.Descriptor instead.
func (*ScriptCommand) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *ScriptCommand) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *ScriptCommand) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ScriptCommand) GetSha256Hash() string {
	if x != nil {
		return x.Sha256Hash
	}
	return ""
}

// Result of script execution
type ScriptResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScriptId      string                 `protobuf:"bytes,1,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`        // ID of the executed script
	Sha256Hash    string                 `protobuf:"bytes,2,opt,name=sha256_hash,json=sha256Hash,proto3" json:"sha256_hash,omitempty"`  // Hash of the executed script
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`       // Exit code from script execution
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`                            // Standard output
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`                            // Standard error
	ExecutedAt    int64                  `protobuf:"varint,6,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"` // Unix timestamp of execution
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptResult) Reset() {
	*x = ScriptResult{}
	mi := &file_proto_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptResult) ProtoMessage() {}

func (x *ScriptResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptResult.ProtoReflect.Descriptor instead.
func (*ScriptResult) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *ScriptResult) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *ScriptResult) GetSha256Hash() string {
	if x != nil {
		return x.Sha256Hash
	}
	return ""
}

func (x *ScriptResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ScriptResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ScriptResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ScriptResult) GetExecutedAt() int64 {
	if x != nil {
		return x.ExecutedAt
	}
	return 0
}

var File_proto_metrics_proto protoreflect.FileDescriptor

const file_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"\x13proto/metrics.proto\x12\ametrics\"\xac\x01\n" +
	"\vHostMetrics\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12%\n" +
	"\x04info\x18\x04 \x01(\v2\x11.metrics.HostInfoR\x04info\x12,\n" +
	"\x05usage\x18\x05 \x01(\v2\x16.metrics.ResourceUsageR\x05usage\"\xac\x01\n" +
	"\bHostInfo\x12%\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x03R\ruptimeSeconds\x12\x1b\n" +
	"\tcpu_cores\x18\x02 \x01(\x05R\bcpuCores\x12,\n" +
	"\x12total_memory_bytes\x18\x03 \x01(\x03R\x10totalMemoryBytes\x12.\n" +
	"\x13total_storage_bytes\x18\x04 \x01(\x03R\x11totalStorageBytes\"\x8a\x01\n" +
	"\rResourceUsage\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12*\n" +
	"\x11used_memory_bytes\x18\x02 \x01(\x03R\x0fusedMemoryBytes\x12,\n" +
	"\x12used_storage_bytes\x18\x03 \x01(\x03R\x10usedStorageBytes\"D\n" +
	"\x0eAcknowledgment\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8b\x01\n" +
	"\x0eOutpostMessage\x120\n" +
	"\ametrics\x18\x01 \x01(\v2\x14.metrics.HostMetricsH\x00R\ametrics\x12<\n" +
	"\rscript_result\x18\x02 \x01(\v2\x15.metrics.ScriptResultH\x00R\fscriptResultB\t\n" +
	"\apayload\"\x8b\x01\n" +
	"\x10CollectorMessage\x12+\n" +
	"\x03ack\x18\x01 \x01(\v2\x17.metrics.AcknowledgmentH\x00R\x03ack\x12?\n" +
	"\x0escript_command\x18\x02 \x01(\v2\x16.metrics.ScriptCommandH\x00R\rscriptCommandB\t\n" +
	"\apayload\"g\n" +
	"\rScriptCommand\x12\x1b\n" +
	"\tscript_id\x18\x01 \x01(\tR\bscriptId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1f\n" +
	"\vsha256_hash\x18\x03 \x01(\tR\n" +
	"sha256Hash\"\xba\x01\n" +
	"\fScriptResult\x12\x1b\n" +
	"\tscript_id\x18\x01 \x01(\tR\bscriptId\x12\x1f\n" +
	"\vsha256_hash\x18\x02 \x01(\tR\n" +
	"sha256Hash\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12\x1f\n" +
	"\vexecuted_at\x18\x06 \x01(\x03R\n" +
	"executedAt2[\n" +
	"\x10MetricsCollector\x12G\n" +
	"\rStreamMetrics\x12\x17.metrics.OutpostMessage\x1a\x19.metrics.CollectorMessage(\x010\x01B(Z&github.com/metorial/command-core/protob\x06proto3"

var (
	file_proto_metrics_proto_rawDescOnce sync.Once
	file_proto_metrics_proto_rawDescData []byte
)

func file_proto_metrics_proto_rawDescGZIP() []byte {
	file_proto_metrics_proto_rawDescOnce.Do(func() {
		file_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metrics_proto_rawDesc), len(file_proto_metrics_proto_rawDesc)))
	})
	return file_proto_metrics_proto_rawDescData
}

var file_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_metrics_proto_goTypes = []any{
	(*HostMetrics)(nil),      // 0: metrics.HostMetrics
	(*HostInfo)(nil),         // 1: metrics.HostInfo
	(*ResourceUsage)(nil),    // 2: metrics.ResourceUsage
	(*Acknowledgment)(nil),   // 3: metrics.Acknowledgment
	(*OutpostMessage)(nil),   // 4: metrics.OutpostMessage
	(*CollectorMessage)(nil), // 5: metrics.CollectorMessage
	(*ScriptCommand)(nil),    // 6: metrics.ScriptCommand
	(*ScriptResult)(nil),     // 7: metrics.ScriptResult
}
var file_proto_metrics_proto_depIdxs = []int32{
	1, // 0: metrics.HostMetrics.info:type_name -> metrics.HostInfo
	2, // 1: metrics.HostMetrics.usage:type_name -> metrics.ResourceUsage
	0, // 2: metrics.OutpostMessage.metrics:type_name -> metrics.HostMetrics
	7, // 3: metrics.OutpostMessage.script_result:type_name -> metrics.ScriptResult
	3, // 4: metrics.CollectorMessage.ack:type_name -> metrics.Acknowledgment
	6, // 5: metrics.CollectorMessage.script_command:type_name -> metrics.ScriptCommand
	4, // 6: metrics.MetricsCollector.StreamMetrics:input_type -> metrics.OutpostMessage
	5, // 7: metrics.MetricsCollector.StreamMetrics:output_type -> metrics.CollectorMessage
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_metrics_proto_init() }
func file_proto_metrics_proto_init() {
	if File_proto_metrics_proto != nil {
		return
	}
	file_proto_metrics_proto_msgTypes[4].OneofWrappers = []any{
		(*OutpostMessage_Metrics)(nil),
		(*OutpostMessage_ScriptResult)(nil),
	}
	file_proto_metrics_proto_msgTypes[5].OneofWrappers = []any{
		(*CollectorMessage_Ack)(nil),
		(*CollectorMessage_ScriptCommand)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metrics_proto_rawDesc), len(file_proto_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metrics_proto_goTypes,
		DependencyIndexes: file_proto_metrics_proto_depIdxs,
		MessageInfos:      file_proto_metrics_proto_msgTypes,
	}.Build()
	File_proto_metrics_proto = out.File
	file_proto_metrics_proto_goTypes = nil
	file_proto_metrics_proto_depIdxs = nil
}
